; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
# Read configuration from environment variables
build_flags = 
    -DWIFI_SSID=\"${sysenv.WIFI_SSID|KL13}\"
    -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD|KeeleriAchu}\"
    -DGITHUB_USERNAME=\"${sysenv.GITHUB_USERNAME|sankerathul}\"
    -DGITHUB_TOKEN=\"${sysenv.GITHUB_TOKEN|}\"
    -DNTP_SERVER=\"${sysenv.NTP_SERVER|pool.ntp.org}\"
    -DGMT_OFFSET=${sysenv.GMT_OFFSET|0}
    -DDAYLIGHT_OFFSET=${sysenv.DAYLIGHT_OFFSET|0}
lib_deps = 
    moononournation/GFX Library for Arduino@1.3.7
    lovyan03/LovyanGFX@^1.1.9
    arduino-libraries/ArduinoHttpClient@^0.4.0
    bblanchon/ArduinoJson@^7.0.0
